name: test

on:
  push:
    branches:
      - main
    paths:
      - '**.js'

jobs:
  run:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Run Action
        uses: ./
